---
# tasks file for mysql

- name: Create mysql database
  community.mysql.mysql_db module:
    name: '{{ wp_mysql_db }}'
    state: present
  become: yes

- name: Create mysql user
  community.mysql.mysql_user:
    name: '{{ wp_mysql_user }}'
    password: '{{ wp_mysql_password }}'
    priv: '*.*:ALL'
  become: yes