---
# tasks file for server

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt:
    name:
      - apache2
      - python3-dev
      - python3-pip
      - mysql-server
      - php-mysql 
      - php
      - libapache2-mod-php
      - python3-mysqldb 
    state: present
  become: yes