Vagrant.configure("2") do |config|
  config.vm.define "ansible-controller" do |controller|
    controller.vm.hostname = "controller"
  end
  config.vm.box = "bento/ubuntu-20.04-arm64"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update -y
    sudo apt install -y software-properties-common
    sudo add-apt-repository --yes --update ppa:ansible/ansible
    sudo apt install -y ansible
  SHELL
end
